# Generated by Django 4.2.2 on 2023-06-23 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_services'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='services',
            new_name='Service',
        ),
    ]
